# Generated by Django 6.1 on 2026-08-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('header', '0003_category_href_logo_href_navbar_href'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_am', models.CharField(max_length=255, verbose_name='Վերնագիր (Հայերեն)')),
                ('title_ru', models.CharField(max_length=255, verbose_name='Վերնագիր (Ռուսերեն)')),
                ('title_en', models.CharField(max_length=255, verbose_name='Վերնագիր (Անգլերեն)')),
                ('description_am', models.TextField(verbose_name='Նկարագրություն (Հայերեն)')),
                ('description_ru', models.TextField(verbose_name='Նկարագրություն (Ռուսերեն)')),
                ('description_en', models.TextField(verbose_name='Նկարագրություն (Անգլերեն)')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('poster', models.ImageField(upload_to='posters/', verbose_name='Պոստեր')),
                ('video_url', models.URLField(verbose_name='Վիդեոյի հղում')),
                ('release_year', models.PositiveIntegerField(verbose_name='Թողարկման տարեթիվ')),
                ('duration', models.PositiveIntegerField(verbose_name='Տևողություն (րոպե)')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Դիտումների քանակ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ստեղծման ամսաթիվ')),
                ('categories', models.ManyToManyField(related_name='movies', to='header.category', verbose_name='Կատեգորիաներ')),
            ],
            options={
                'verbose_name': 'Ֆիլմ',
                'verbose_name_plural': 'Ֆիլմեր',
                'ordering': ['-created_at'],
            },
        ),
    ]
