# Generated by Django 6.1 on 2026-09-03 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='video_url',
            field=models.URLField(max_length=1000, verbose_name='Վիդեոյի հղում'),
        ),
    ]
