# Generated by Django 6.1 on 2026-09-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0002_alter_movie_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.FileField(upload_to='posters/', verbose_name='Պոստեր'),
        ),
    ]
