# Generated by Django 6.1 on 2026-09-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0003_alter_movie_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='telegram_message_id',
            field=models.IntegerField(blank=True, help_text='The exact message ID of the video in the Telegram channel', null=True, verbose_name='Telegram Message ID'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='video_url',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='Վիդեոյի հղում'),
        ),
    ]
