# Generated by Django 6.1.1 on 2026-09-03 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0004_movie_telegram_message_id_alter_movie_video_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_am', models.CharField(blank=True, max_length=255, null=True, verbose_name='Անուն (Հայերեն)')),
                ('name_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Անուն (Ռուսերեն)')),
                ('name_en', models.CharField(max_length=255, verbose_name='Անուն (Անգլերեն)')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='actors/', verbose_name='Նկար')),
            ],
            options={
                'verbose_name': 'Դերասան',
                'verbose_name_plural': 'Դերասաններ',
                'ordering': ['name_en'],
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(blank=True, related_name='movies', to='film.actor', verbose_name='Դերասաններ'),
        ),
    ]
