# Generated by Django 6.1.1 on 2026-09-03 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0005_actor_movie_actors'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='tmdb_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='TMDB ID'),
        ),
    ]
