# Generated by Django 6.1.1 on 2026-09-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0006_movie_tmdb_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageMovies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(max_length=1000, upload_to='HomePageMovies/')),
                ('video', models.FileField(max_length=1000, upload_to='HomePageMovies/')),
            ],
        ),
    ]
