# Generated by Django 6.1.1 on 2026-09-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0007_homepagemovies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagemovies',
            name='images',
            field=models.FileField(blank=True, max_length=1000, null=True, upload_to='HomePageMovies/'),
        ),
        migrations.AlterField(
            model_name='homepagemovies',
            name='video',
            field=models.FileField(blank=True, max_length=1000, null=True, upload_to='HomePageMovies/'),
        ),
    ]
