# Generated by Django 6.1.1 on 2026-09-05 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0008_alter_homepagemovies_images_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_caption', models.TextField(blank=True, null=True, verbose_name='Original Caption')),
                ('telegram_message_id', models.IntegerField(unique=True, verbose_name='Telegram Message ID')),
                ('source_channel', models.CharField(max_length=255, verbose_name='Source Channel')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Is Processed')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Raw Movie',
                'verbose_name_plural': 'Raw Movies',
                'ordering': ['-created_at'],
            },
        ),
    ]
