# Generated by Django 6.1.1 on 2026-09-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0009_rawmovie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='episode_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Սերիա'),
        ),
        migrations.AddField(
            model_name='movie',
            name='is_series',
            field=models.BooleanField(default=False, verbose_name='Սերիալ'),
        ),
        migrations.AddField(
            model_name='movie',
            name='season_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Սեզոն'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tmdb_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='TMDB ID'),
        ),
    ]
