# Generated by Django 6.1.1 on 2026-09-05 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0010_movie_episode_number_movie_is_series_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmovie',
            name='manual_is_tv',
            field=models.BooleanField(default=False, help_text='Check this if the manual_tmdb_id is for a TV show.', verbose_name='Manual is TV?'),
        ),
        migrations.AddField(
            model_name='rawmovie',
            name='manual_tmdb_id',
            field=models.IntegerField(blank=True, help_text='Paste TMDB ID here to force the exact movie/TV show.', null=True, verbose_name='Manual TMDB ID'),
        ),
    ]
