# Generated by Django 6.1.1 on 2026-09-05 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0011_rawmovie_manual_is_tv_rawmovie_manual_tmdb_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmovie',
            name='manual_is_tv',
            field=models.BooleanField(blank=True, default=False, help_text='Check this if the manual_tmdb_id is for a TV show.', null=True, verbose_name='Manual is TV?'),
        ),
    ]
