# Generated by Django 6.1.1 on 2026-09-06 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0012_alter_rawmovie_manual_is_tv'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Վերնագիր')),
                ('content', models.TextField(verbose_name='Բովանդակություն')),
                ('image_url', models.URLField(blank=True, max_length=1000, null=True, verbose_name='Նկարի հղում')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ստեղծման ամսաթիվ')),
                ('generated_by_ai', models.BooleanField(default=True, verbose_name='Գեներացված է AI-ի կողմից')),
            ],
            options={
                'verbose_name': 'Նորություն',
                'verbose_name_plural': 'Նորություններ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=255, verbose_name='Հեղինակի անուն')),
                ('text', models.TextField(verbose_name='Մեկնաբանություն')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ստեղծման ամսաթիվ')),
                ('news_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='film.newspost', verbose_name='Նորություն')),
            ],
            options={
                'verbose_name': 'Մեկնաբանություն',
                'verbose_name_plural': 'Մեկնաբանություններ',
                'ordering': ['-created_at'],
            },
        ),
    ]
