# Generated by Django 6.1.1 on 2026-09-06 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0013_newspost_newscomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsComment',
        ),
        migrations.DeleteModel(
            name='NewsPost',
        ),
    ]
