import { getNewsById } from "@/lib/api";
import { getLang } from "@/lib/lang";
import Link from "next/link";
import CommentSection from "@/components/news/CommentSection";
import { notFound } from "next/navigation";
interface NewsDetailPageProps {
    params: Promise<{
        id: string;
    }>;
}

export const metadata = {
    title: "Kino News",
    description: "Watch news online for free"
};

const t = {
    am: {
        back: "\u054e\u0565\u0580\u0561\u0564\u0561\u057c\u0576\u0561\u056c \u0576\u0578\u0580\u0578\u0582\u0569\u0575\u0578\u0582\u0576\u0576\u0565\u0580\u056b\u0576",
        aiBadge: "\u0533\u0565\u0576\u0565\u0580\u0561\u0581\u057e\u0561\u056e \u0567 AI-\u056b \u056f\u0578\u0572\u0574\u056b\u0581",
    },
    ru: {
        back: "\u041d\u0430\u0437\u0430\u0434 \u043a \u043d\u043e\u0432\u043e\u0441\u0442\u044f\u043c",
        aiBadge: "\u0421\u0433\u0435\u043d\u0435\u0440\u0438\u0440\u043e\u0432\u0430\u043d\u043e AI",
    },
    en: {
        back: "Back to News",
        aiBadge: "Generated by AI",
    }
};

export default async function NewsDetailPage({ params }: NewsDetailPageProps) {
    const { id } = await params;
    const lang = await getLang();
    const post = await getNewsById(id);
    const tr = t[lang as keyof typeof t] || t.en;
    const dateLocale = lang === 'am' ? 'hy-AM' : lang === 'ru' ? 'ru-RU' : 'en-US';

    if (!post) {
        notFound();
    }

    return (
        <div className="container mx-auto px-4 py-8 max-w-4xl">
            <Link href="/news" className="inline-flex items-center text-blue-400 hover:text-blue-300 mb-8 transition-colors group">
                <svg className="w-5 h-5 mr-2 transform group-hover:-translate-x-1 transition-transform" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 19l-7-7m0 0l7-7m-7 7h18" />
                </svg>
                {tr.back}
            </Link>

            <article className="bg-[#1a1d24]/40 rounded-3xl p-6 md:p-10 border border-gray-800 shadow-2xl">
                <header className="mb-8">
                    <h1 className="text-3xl md:text-5xl font-bold text-white mb-4 leading-tight">
                        {post.title}
                    </h1>
                    <div className="flex flex-wrap items-center text-gray-400 text-sm gap-4 border-b border-gray-800 pb-6">
                        <span className="flex items-center">
                            <svg className="w-4 h-4 mr-1.5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
                            </svg>
                            {new Date(post.created_at).toLocaleDateString(dateLocale, { year: 'numeric', month: 'long', day: 'numeric' })}
                        </span>
                        
                        {post.generated_by_ai && (
                            <span className="bg-blue-900/40 text-blue-400 px-2.5 py-1 rounded-md border border-blue-800/50 flex items-center">
                                <svg className="w-3.5 h-3.5 mr-1" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 10V3L4 14h7v7l9-11h-7z" />
                                </svg>
                                {tr.aiBadge}
                            </span>
                        )}
                    </div>
                </header>

                {post.image_url && (
                    <div className="w-full h-[400px] relative rounded-2xl overflow-hidden mb-10 shadow-lg">
                        {/* eslint-disable-next-line @next/next/no-img-element */}
                        <img 
                            src={post.image_url} 
                            alt={post.title} 
                            className="w-full h-full object-cover"
                        />
                    </div>
                )}

                <div className="prose prose-invert prose-lg max-w-none prose-p:text-gray-300 prose-p:leading-relaxed prose-headings:text-white prose-a:text-blue-400 hover:prose-a:text-blue-300">
                    {post.content.split('\n').map((paragraph, index) => (
                        paragraph.trim() ? <p key={index} className="mb-6">{paragraph}</p> : null
                    ))}
                </div>

                <CommentSection newsId={post.id} initialComments={post.comments} lang={lang} />
            </article>
        </div>
    );
}
