import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/header";
import AIChat from "@/components/ai_search/AIChat";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { getLang } from "@/lib/lang";
export const Metadata: Metadata = {
  title: "KinoGid",
  description:"watch movies online for free"
  
};

export default async function RootLayout({ children }: LayoutProps<"/">) {
  const lang = await getLang();

  return (
    <html lang={lang}>
      <body className=" bg-black">
        <Header />
        {children}
        <AIChat lang={lang} />
      </body>
    </html>
  );
}
