# Generated by Django 6.1 on 2026-08-26 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Navbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Վերնագիր')),
                ('slug', models.SlugField()),
                ('lang', models.CharField(default='am', max_length=2, verbose_name='Լեզու')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('slug', 'lang')},
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Կատեգորիայի անուն')),
                ('slug', models.SlugField()),
                ('lang', models.CharField(default='am', max_length=2, verbose_name='Լեզու')),
                ('navbar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='header.navbar')),
            ],
            options={
                'unique_together': {('slug', 'lang')},
            },
        ),
    ]
