# Generated by Django 6.1 on 2026-08-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0002_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='href',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ուղղորդում'),
        ),
        migrations.AddField(
            model_name='logo',
            name='href',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='navbar',
            name='href',
            field=models.CharField(default='', max_length=200, verbose_name='Ուղղորդում'),
            preserve_default=False,
        ),
    ]
