# Generated by Django 6.1.1 on 2026-09-04 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0003_category_href_logo_href_navbar_href'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbar',
            name='href',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ուղղորդում'),
        ),
    ]
